version: '3.7'
services:
  carpooling-backend:
    image: bbernovici/carpooling
    ports:
      - "8080:8080"
    environment:
      - SERVICE_PORTS=8080
    depends_on:
      - mongodb
      - neo4j
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    networks:
      - backend-network

  proxy:
    image: dockercloud/haproxy
    depends_on:
      - carpooling-backend
    environment:
      - BALANCE=leastconn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8081:80
    networks:
      - backend-network
    deploy:
      placement:
        constraints: [node.role == manager]

  mongodb:
    image: mongo:4.0.2
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null

  neo4j:
    image: neo4j:3.4.7
    ports:
      - "17474:7474"
    volumes:
      - ./db/dbms:/data/dbms

networks:
  backend-network:
    driver: overlay

rabbitmq:
  image: rabbitmq:management
  ports:
    - "5672:5672"
    - "15672:15672"
